[GENERAL]
ACTIVE_CONFIGURATION=SEN4CAP
SERVICES_ARCHIVE=eo-data-services-1.1.4-20250605_s4c.zip
INSTALL_SNAP=0
INSTALL_CCI_LC=0
SUPPORTED_PROFILES=sen2agri,sen4cap
USE_SEN2AGRI_IN_SERVICE_NAMES = 0
PROJECT_NAME=NotSet
DB_NAME=sen4cap
DB_HOST=localhost
REQUIRED_PROCESSORS=1,15,21,24
REQUIRED_CONFIG_CATEGORIES=1,2,7,8,12,13,14,15,17,27,31,32
REQUIRED_PRODUCT_TYPES=1,25,26
SERVICES_PORT=8080
HTTP_LISTENER_PORT=8082
ORCHESTRATOR_HTTP_LISTEN_PORT=8083
EXECUTOR_HTTP_LISTEN_PORT=8084
EXECUTOR_LISTEN_PORT=7777

[SEN4CAP]
CONFIGURATION_NAME=sen4cap
PROFILES=sen4cap
DB_NAME=sen4cap
SERVICES_ARCHIVE=eo-data-services-1.1.4-20250605_s4c.zip
USE_SEN2AGRI_IN_SERVICE_NAMES = 1
PROJECT_NAME=Sen4CAP
REQUIRED_PROCESSORS=3,7,8,9,10,11,14,15,21,25,26,28
REQUIRED_CONFIG_CATEGORIES=4,19,20,21,22,23,26,27,32,36,37,40
REQUIRED_PRODUCT_TYPES=3,10,11,12,13,14,15,17,18,19,20,21,22,23,24,26,33,35
REQUIRED_AUXDATA_DESCRIPTORS=1,2,3,4,5,6,7
USER_NAME=sen4cap
USER_MAIL=sen4cap@c-s.ro
USER_PASS=sen4cap
SERVICES_PORT=8080
HTTP_LISTENER_PORT=8082
ORCHESTRATOR_HTTP_LISTEN_PORT=8083
EXECUTOR_HTTP_LISTEN_PORT=8084
EXECUTOR_LISTEN_PORT=7777

[SEN4STAT]
CONFIGURATION_NAME=sen4stat
PROFILES=sen4stat
DB_NAME=sen4stat
SERVICES_ARCHIVE=eo-data-services-1.6.0-20251208_s4s.zip
USE_SEN2AGRI_IN_SERVICE_NAMES=1
PROJECT_NAME=Sen4Stat
REQUIRED_PROCESSORS=2,3,7,8,14,16,17,18,20,27
REQUIRED_CONFIG_CATEGORIES=3,4,21,23,26,28,29,30,31,38,39
REQUIRED_PRODUCT_TYPES=2,3,10,11,14,17,18,19,20,21,22,23,25,26,27,28,29,32,34,36,37,38,39,40,41,42,43
REQUIRED_AUXDATA_DESCRIPTORS=8,9,10,12
USER_NAME=sen4stat
USER_MAIL=sen4stat@c-s.ro
USER_PASS=sen4stat
