CREATE TABLE "shape_tiles_l8" (gid serial primary key,
"area" numeric,
"perimeter" numeric,
"pr_" float8,
"pr_id" float8,
"rings_ok" int4,
"rings_nok" int4,
"wrspr" float8,
"pr" int4,
"path" int2,
"row" int2,
"mode" varchar(1),
"dayclass" int2,
"sequence" int4,
"geog" geography(MULTIPOLYGON,4326));
