# FROM python:3.11-slim
FROM sefrem/sen4cap-s1l2-preprocessing-v1:1.2

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    libgeos-dev \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv

WORKDIR /app
COPY . .

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT []